[package]
name = "safe-girepository"
edition.workspace = true
license.workspace = true
version.workspace = true
build = "build.rs"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[[bin]]
name = "gi-compile-repository"
path = "src/bin/gi_compile_repository.rs"

[[bin]]
name = "gi-decompile-typelib"
path = "src/bin/gi_decompile_typelib.rs"

[[bin]]
name = "gi-inspect-typelib"
path = "src/bin/gi_inspect_typelib.rs"
