debian/cross-tools/${DEB_HOST_GNU_TYPE}-gi-* usr/bin
debian/cross-tools/deb-can-run usr/lib/${DEB_HOST_MULTIARCH}/glib-2.0
usr/bin/gi-compile-repository usr/lib/${DEB_HOST_MULTIARCH}/glib-2.0
usr/bin/gi-decompile-typelib usr/lib/${DEB_HOST_MULTIARCH}/glib-2.0
usr/bin/gi-inspect-typelib usr/lib/${DEB_HOST_MULTIARCH}/glib-2.0
usr/include/gio-unix-2.0
usr/include/glib-2.0/gio
usr/include/glib-2.0/glib
usr/include/glib-2.0/glib-object.h
usr/include/glib-2.0/glib-unix.h
usr/include/glib-2.0/glib.h
usr/include/glib-2.0/gmodule
usr/include/glib-2.0/gmodule.h
usr/include/glib-2.0/gobject
usr/lib/*/glib-2.0/include/glibconfig.h
usr/lib/*/libgio-2.0.a
usr/lib/*/libgio-2.0.so
usr/lib/*/libglib-2.0.a
usr/lib/*/libglib-2.0.so
usr/lib/*/libgmodule-2.0.a
usr/lib/*/libgmodule-2.0.so
usr/lib/*/libgobject-2.0.a
usr/lib/*/libgobject-2.0.so
usr/lib/*/libgthread-2.0.a
usr/lib/*/libgthread-2.0.so
usr/lib/*/pkgconfig/gio-2.0.pc
usr/lib/*/pkgconfig/gio-unix-2.0.pc
usr/lib/*/pkgconfig/glib-2.0.pc
usr/lib/*/pkgconfig/gmodule-2.0.pc
usr/lib/*/pkgconfig/gmodule-export-2.0.pc
usr/lib/*/pkgconfig/gmodule-no-export-2.0.pc
usr/lib/*/pkgconfig/gobject-2.0.pc
usr/lib/*/pkgconfig/gthread-2.0.pc
usr/share/gdb
usr/share/gettext/its
usr/share/glib-2.0/dtds
usr/share/glib-2.0/gdb
usr/share/glib-2.0/schemas
usr/share/glib-2.0/valgrind
