extern "C" {
    pub type _IO_wide_data;
    pub type _IO_codecvt;
    pub type _IO_marker;
    fn signal(__sig: ::core::ffi::c_int, __handler: __sighandler_t) -> __sighandler_t;
    fn close(__fd: ::core::ffi::c_int) -> ::core::ffi::c_int;
    fn read(__fd: ::core::ffi::c_int, __buf: *mut ::core::ffi::c_void, __nbytes: size_t)
        -> ssize_t;
    fn write(__fd: ::core::ffi::c_int, __buf: *const ::core::ffi::c_void, __n: size_t) -> ssize_t;
    fn pipe(__pipedes: *mut ::core::ffi::c_int) -> ::core::ffi::c_int;
    fn pipe2(__pipedes: *mut ::core::ffi::c_int, __flags: ::core::ffi::c_int)
        -> ::core::ffi::c_int;
    fn dup(__fd: ::core::ffi::c_int) -> ::core::ffi::c_int;
    fn execvp(
        __file: *const ::core::ffi::c_char,
        __argv: *const *mut ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
    fn _exit(__status: ::core::ffi::c_int) -> !;
    fn getpid() -> __pid_t;
    fn fork() -> __pid_t;
    fn isatty(__fd: ::core::ffi::c_int) -> ::core::ffi::c_int;
    static mut safe_c2rust_stdin: *mut FILE;
    static mut safe_c2rust_stdout: *mut FILE;
    fn fflush(__stream: *mut FILE) -> ::core::ffi::c_int;
    fn fprintf(
        __stream: *mut FILE,
        __format: *const ::core::ffi::c_char,
        ...
    ) -> ::core::ffi::c_int;
    fn sprintf(
        __s: *mut ::core::ffi::c_char,
        __format: *const ::core::ffi::c_char,
        ...
    ) -> ::core::ffi::c_int;
    fn snprintf(
        __s: *mut ::core::ffi::c_char,
        __maxlen: size_t,
        __format: *const ::core::ffi::c_char,
        ...
    ) -> ::core::ffi::c_int;
    fn fgets(
        __s: *mut ::core::ffi::c_char,
        __n: ::core::ffi::c_int,
        __stream: *mut FILE,
    ) -> *mut ::core::ffi::c_char;
    fn perror(__s: *const ::core::ffi::c_char);
    fn select(
        __nfds: ::core::ffi::c_int,
        __readfds: *mut fd_set,
        __writefds: *mut fd_set,
        __exceptfds: *mut fd_set,
        __timeout: *mut timeval,
    ) -> ::core::ffi::c_int;
    fn __errno_location() -> *mut ::core::ffi::c_int;
    fn fcntl(__fd: ::core::ffi::c_int, __cmd: ::core::ffi::c_int, ...) -> ::core::ffi::c_int;
    fn waitpid(
        __pid: __pid_t,
        __stat_loc: *mut ::core::ffi::c_int,
        __options: ::core::ffi::c_int,
    ) -> __pid_t;
    fn strcpy(
        __dest: *mut ::core::ffi::c_char,
        __src: *const ::core::ffi::c_char,
    ) -> *mut ::core::ffi::c_char;
    fn strerror_r(
        __errnum: ::core::ffi::c_int,
        __buf: *mut ::core::ffi::c_char,
        __buflen: size_t,
    ) -> *mut ::core::ffi::c_char;
    fn g_get_prgname() -> *const gchar;
}
pub type size_t = usize;
pub type gssize = ::core::ffi::c_long;
pub type gsize = ::core::ffi::c_ulong;
pub type __off_t = ::core::ffi::c_long;
pub type __off64_t = ::core::ffi::c_long;
pub type __pid_t = ::core::ffi::c_int;
pub type __time_t = ::core::ffi::c_long;
pub type __suseconds_t = ::core::ffi::c_long;
pub type __ssize_t = ::core::ffi::c_long;
pub type pid_t = __pid_t;
pub type __sighandler_t = Option<unsafe extern "C" fn(::core::ffi::c_int) -> ()>;
pub type ssize_t = __ssize_t;
#[derive(Copy, Clone)]
#[repr(C)]
pub struct _IO_FILE {
    pub _flags: ::core::ffi::c_int,
    pub _IO_read_ptr: *mut ::core::ffi::c_char,
    pub _IO_read_end: *mut ::core::ffi::c_char,
    pub _IO_read_base: *mut ::core::ffi::c_char,
    pub _IO_write_base: *mut ::core::ffi::c_char,
    pub _IO_write_ptr: *mut ::core::ffi::c_char,
    pub _IO_write_end: *mut ::core::ffi::c_char,
    pub _IO_buf_base: *mut ::core::ffi::c_char,
    pub _IO_buf_end: *mut ::core::ffi::c_char,
    pub _IO_save_base: *mut ::core::ffi::c_char,
    pub _IO_backup_base: *mut ::core::ffi::c_char,
    pub _IO_save_end: *mut ::core::ffi::c_char,
    pub _markers: *mut _IO_marker,
    pub _chain: *mut _IO_FILE,
    pub _fileno: ::core::ffi::c_int,
    pub _flags2: ::core::ffi::c_int,
    pub _old_offset: __off_t,
    pub _cur_column: ::core::ffi::c_ushort,
    pub _vtable_offset: ::core::ffi::c_schar,
    pub _shortbuf: [::core::ffi::c_char; 1],
    pub _lock: *mut ::core::ffi::c_void,
    pub _offset: __off64_t,
    pub _codecvt: *mut _IO_codecvt,
    pub _wide_data: *mut _IO_wide_data,
    pub _freeres_list: *mut _IO_FILE,
    pub _freeres_buf: *mut ::core::ffi::c_void,
    pub __pad5: size_t,
    pub _mode: ::core::ffi::c_int,
    pub _unused2: [::core::ffi::c_char; 20],
}
pub type _IO_lock_t = ();
pub type FILE = _IO_FILE;
#[derive(Copy, Clone)]
#[repr(C)]
pub struct timeval {
    pub tv_sec: __time_t,
    pub tv_usec: __suseconds_t,
}
pub type __fd_mask = ::core::ffi::c_long;
#[derive(Copy, Clone)]
#[repr(C)]
pub struct fd_set {
    pub fds_bits: [__fd_mask; 16],
}
pub type gchar = ::core::ffi::c_char;
pub type gint = ::core::ffi::c_int;
pub type gboolean = gint;
pub type guint = ::core::ffi::c_uint;
pub type gconstpointer = *const ::core::ffi::c_void;
pub const FALSE: ::core::ffi::c_int = 0 as ::core::ffi::c_int;
pub const TRUE: ::core::ffi::c_int = (FALSE == 0) as ::core::ffi::c_int;
pub const __FD_SETSIZE: ::core::ffi::c_int = 1024 as ::core::ffi::c_int;
pub const SIGCHLD: ::core::ffi::c_int = 17 as ::core::ffi::c_int;
pub const NULL: *mut ::core::ffi::c_void = ::core::ptr::null_mut::<::core::ffi::c_void>();
pub const __NFDBITS: ::core::ffi::c_int =
    8 as ::core::ffi::c_int * ::core::mem::size_of::<__fd_mask>() as ::core::ffi::c_int;
pub const FD_SETSIZE: ::core::ffi::c_int = __FD_SETSIZE;
pub const ENOSYS: ::core::ffi::c_int = 38 as ::core::ffi::c_int;
pub const O_NONBLOCK: ::core::ffi::c_int = 0o4000 as ::core::ffi::c_int;
pub const __O_CLOEXEC: ::core::ffi::c_int = 0o2000000 as ::core::ffi::c_int;
pub const O_CLOEXEC: ::core::ffi::c_int = __O_CLOEXEC;
pub const F_GETFD: ::core::ffi::c_int = 1 as ::core::ffi::c_int;
pub const F_SETFD: ::core::ffi::c_int = 2 as ::core::ffi::c_int;
pub const F_SETFL: ::core::ffi::c_int = 4 as ::core::ffi::c_int;
pub const FD_CLOEXEC: ::core::ffi::c_int = 1 as ::core::ffi::c_int;
#[inline]
unsafe extern "C" fn safe_c2rust_g_unix_open_pipe_internal(
    mut fds: *mut ::core::ffi::c_int,
    mut close_on_exec: gboolean,
    mut nonblock: gboolean,
) -> gboolean {
    let mut ecode: ::core::ffi::c_int = 0;
    let mut flags: ::core::ffi::c_int = 0 as ::core::ffi::c_int;
    if close_on_exec != 0 {
        flags |= O_CLOEXEC;
    }
    if nonblock != 0 {
        flags |= O_NONBLOCK;
    }
    ecode = pipe2(fds as *mut ::core::ffi::c_int, flags);
    if ecode == -(1 as ::core::ffi::c_int) && *__errno_location() != ENOSYS {
        return FALSE;
    } else if ecode == 0 as ::core::ffi::c_int {
        return TRUE;
    }
    if pipe(fds as *mut ::core::ffi::c_int) == -(1 as ::core::ffi::c_int) {
        return FALSE;
    }
    if close_on_exec != 0 {
        if fcntl(
            *fds.offset(0 as ::core::ffi::c_int as isize),
            F_SETFD,
            FD_CLOEXEC,
        ) == -(1 as ::core::ffi::c_int)
            || fcntl(
                *fds.offset(1 as ::core::ffi::c_int as isize),
                F_SETFD,
                FD_CLOEXEC,
            ) == -(1 as ::core::ffi::c_int)
        {
            let mut saved_errno: ::core::ffi::c_int = *__errno_location();
            close(*fds.offset(0 as ::core::ffi::c_int as isize));
            close(*fds.offset(1 as ::core::ffi::c_int as isize));
            *fds.offset(0 as ::core::ffi::c_int as isize) = -(1 as ::core::ffi::c_int);
            *fds.offset(1 as ::core::ffi::c_int as isize) = -(1 as ::core::ffi::c_int);
            *__errno_location() = saved_errno;
            return FALSE;
        }
    }
    if nonblock != 0 {
        let mut flags_0: ::core::ffi::c_int = O_NONBLOCK;
        if fcntl(
            *fds.offset(0 as ::core::ffi::c_int as isize),
            F_SETFL,
            flags_0,
        ) == -(1 as ::core::ffi::c_int)
            || fcntl(
                *fds.offset(1 as ::core::ffi::c_int as isize),
                F_SETFL,
                flags_0,
            ) == -(1 as ::core::ffi::c_int)
        {
            let mut saved_errno_0: ::core::ffi::c_int = *__errno_location();
            close(*fds.offset(0 as ::core::ffi::c_int as isize));
            close(*fds.offset(1 as ::core::ffi::c_int as isize));
            *fds.offset(0 as ::core::ffi::c_int as isize) = -(1 as ::core::ffi::c_int);
            *fds.offset(1 as ::core::ffi::c_int as isize) = -(1 as ::core::ffi::c_int);
            *__errno_location() = saved_errno_0;
            return FALSE;
        }
    }
    return TRUE;
}
pub const DEBUGGER: [::core::ffi::c_char; 4] =
    unsafe { ::core::mem::transmute::<[u8; 4], [::core::ffi::c_char; 4]>(*b"gdb\0") };
#[no_mangle]
pub static mut safe_c2rust_glib_on_error_halt: gboolean = TRUE;
#[no_mangle]
pub unsafe extern "C" fn safe_c2rust_g_on_error_query(mut prg_name: *const gchar) {
    static mut safe_c2rust_query1: *const gchar = b"[E]xit, [H]alt\0" as *const u8 as *const gchar;
    static mut safe_c2rust_query2: *const gchar =
        b", show [S]tack trace\0" as *const u8 as *const gchar;
    static mut safe_c2rust_query3: *const gchar = b" or [P]roceed\0" as *const u8 as *const gchar;
    let mut buf: [gchar; 16] = [0; 16];
    if prg_name.is_null() {
        prg_name = g_get_prgname();
    }
    loop {
        if !prg_name.is_null() {
            fprintf(
                safe_c2rust_stdout,
                b"%s (pid:%u): %s%s%s: \0" as *const u8 as *const ::core::ffi::c_char,
                prg_name,
                getpid() as guint,
                safe_c2rust_query1,
                safe_c2rust_query2,
                safe_c2rust_query3,
            );
        } else {
            fprintf(
                safe_c2rust_stdout,
                b"(process:%u): %s%s: \0" as *const u8 as *const ::core::ffi::c_char,
                getpid() as guint,
                safe_c2rust_query1,
                safe_c2rust_query3,
            );
        }
        fflush(safe_c2rust_stdout);
        if isatty(0 as ::core::ffi::c_int) != 0 && isatty(1 as ::core::ffi::c_int) != 0 {
            if fgets(
                &raw mut buf as *mut ::core::ffi::c_char,
                8 as ::core::ffi::c_int,
                safe_c2rust_stdin,
            )
            .is_null()
            {
                _exit(0 as ::core::ffi::c_int);
            }
        } else {
            strcpy(
                &raw mut buf as *mut ::core::ffi::c_char,
                b"E\n\0" as *const u8 as *const ::core::ffi::c_char,
            );
        }
        if (buf[0 as ::core::ffi::c_int as usize] as ::core::ffi::c_int == 'E' as i32
            || buf[0 as ::core::ffi::c_int as usize] as ::core::ffi::c_int == 'e' as i32)
            && buf[1 as ::core::ffi::c_int as usize] as ::core::ffi::c_int == '\n' as i32
        {
            _exit(0 as ::core::ffi::c_int);
        } else if (buf[0 as ::core::ffi::c_int as usize] as ::core::ffi::c_int == 'P' as i32
            || buf[0 as ::core::ffi::c_int as usize] as ::core::ffi::c_int == 'p' as i32)
            && buf[1 as ::core::ffi::c_int as usize] as ::core::ffi::c_int == '\n' as i32
        {
            return;
        } else if !prg_name.is_null()
            && (buf[0 as ::core::ffi::c_int as usize] as ::core::ffi::c_int == 'S' as i32
                || buf[0 as ::core::ffi::c_int as usize] as ::core::ffi::c_int == 's' as i32)
            && buf[1 as ::core::ffi::c_int as usize] as ::core::ffi::c_int == '\n' as i32
        {
            safe_c2rust_g_on_error_stack_trace(prg_name);
        } else {
            if !((buf[0 as ::core::ffi::c_int as usize] as ::core::ffi::c_int == 'H' as i32
                || buf[0 as ::core::ffi::c_int as usize] as ::core::ffi::c_int == 'h' as i32)
                && buf[1 as ::core::ffi::c_int as usize] as ::core::ffi::c_int == '\n' as i32)
            {
                continue;
            }
            while safe_c2rust_glib_on_error_halt != 0 {}
            ::core::ptr::write_volatile(
                &mut safe_c2rust_glib_on_error_halt as *mut gboolean,
                TRUE as gboolean,
            );
            return;
        }
    }
}
#[no_mangle]
pub unsafe extern "C" fn safe_c2rust_g_on_error_stack_trace(mut prg_name: *const gchar) {
    let mut pid: pid_t = 0;
    let mut buf: [gchar; 16] = [0; 16];
    let mut args: [*const gchar; 5] = [
        DEBUGGER.as_ptr(),
        ::core::ptr::null::<gchar>(),
        ::core::ptr::null::<gchar>(),
        ::core::ptr::null::<gchar>(),
        ::core::ptr::null::<gchar>(),
    ];
    let mut status: ::core::ffi::c_int = 0;
    if prg_name.is_null() {
        return;
    }
    sprintf(
        &raw mut buf as *mut ::core::ffi::c_char,
        b"%u\0" as *const u8 as *const ::core::ffi::c_char,
        getpid() as guint,
    );
    args[1 as ::core::ffi::c_int as usize] = prg_name;
    args[2 as ::core::ffi::c_int as usize] = &raw mut buf as *mut gchar;
    pid = fork() as pid_t;
    if pid == 0 as ::core::ffi::c_int {
        safe_c2rust_stack_trace(
            &raw mut args as *mut *const gchar as *const *const ::core::ffi::c_char,
        );
        _exit(0 as ::core::ffi::c_int);
    } else if pid == -(1 as ::core::ffi::c_int) {
        perror(b"unable to fork gdb\0" as *const u8 as *const ::core::ffi::c_char);
        return;
    }
    loop {
        let mut retval: pid_t =
            waitpid(pid as __pid_t, &raw mut status, 0 as ::core::ffi::c_int) as pid_t;
        if retval as ::core::ffi::c_int & 0x7f as ::core::ffi::c_int == 0 as ::core::ffi::c_int
            || ((retval as ::core::ffi::c_int & 0x7f as ::core::ffi::c_int)
                + 1 as ::core::ffi::c_int) as ::core::ffi::c_schar
                as ::core::ffi::c_int
                >> 1 as ::core::ffi::c_int
                > 0 as ::core::ffi::c_int
        {
            break;
        }
    }
}
static mut safe_c2rust_stack_trace_done: gboolean = FALSE;
unsafe extern "C" fn safe_c2rust_stack_trace_sigchld(mut signum: ::core::ffi::c_int) {
    safe_c2rust_stack_trace_done = TRUE as gboolean;
}
pub const BUFSIZE: ::core::ffi::c_int = 1024 as ::core::ffi::c_int;
#[inline]
unsafe extern "C" fn safe_c2rust_get_strerror(
    mut buffer: *mut ::core::ffi::c_char,
    mut n: gsize,
) -> *const ::core::ffi::c_char {
    return strerror_r(*__errno_location(), buffer, n as size_t);
}
unsafe extern "C" fn safe_c2rust_checked_write(
    mut fd: ::core::ffi::c_int,
    mut buf: gconstpointer,
    mut n: gsize,
) -> gssize {
    let mut written: gssize = write(fd, buf as *const ::core::ffi::c_void, n as size_t) as gssize;
    if written == -(1 as ::core::ffi::c_int) as gssize {
        let mut msg: [::core::ffi::c_char; 1024] = [
            0 as ::core::ffi::c_int as ::core::ffi::c_char,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ];
        let mut error_str: [::core::ffi::c_char; 512] = [
            0 as ::core::ffi::c_int as ::core::ffi::c_char,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ];
        safe_c2rust_get_strerror(
            &raw mut error_str as *mut ::core::ffi::c_char,
            (::core::mem::size_of::<[::core::ffi::c_char; 512]>() as gsize)
                .wrapping_sub(1 as gsize),
        );
        snprintf(
            &raw mut msg as *mut ::core::ffi::c_char,
            (::core::mem::size_of::<[::core::ffi::c_char; 1024]>() as size_t)
                .wrapping_sub(1 as size_t),
            b"Unable to write to fd %d: %s\0" as *const u8 as *const ::core::ffi::c_char,
            fd,
            &raw mut error_str as *mut ::core::ffi::c_char,
        );
        perror(&raw mut msg as *mut ::core::ffi::c_char);
        _exit(0 as ::core::ffi::c_int);
    }
    return written;
}
unsafe extern "C" fn safe_c2rust_checked_dup(mut fd: ::core::ffi::c_int) -> ::core::ffi::c_int {
    let mut new_fd: ::core::ffi::c_int = dup(fd);
    if new_fd == -(1 as ::core::ffi::c_int) {
        let mut msg: [::core::ffi::c_char; 1024] = [
            0 as ::core::ffi::c_int as ::core::ffi::c_char,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ];
        let mut error_str: [::core::ffi::c_char; 512] = [
            0 as ::core::ffi::c_int as ::core::ffi::c_char,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ];
        safe_c2rust_get_strerror(
            &raw mut error_str as *mut ::core::ffi::c_char,
            (::core::mem::size_of::<[::core::ffi::c_char; 512]>() as gsize)
                .wrapping_sub(1 as gsize),
        );
        snprintf(
            &raw mut msg as *mut ::core::ffi::c_char,
            (::core::mem::size_of::<[::core::ffi::c_char; 1024]>() as size_t)
                .wrapping_sub(1 as size_t),
            b"Unable to duplicate fd %d: %s\0" as *const u8 as *const ::core::ffi::c_char,
            fd,
            &raw mut error_str as *mut ::core::ffi::c_char,
        );
        perror(&raw mut msg as *mut ::core::ffi::c_char);
        _exit(0 as ::core::ffi::c_int);
    }
    return new_fd;
}
unsafe extern "C" fn safe_c2rust_stack_trace(mut args: *const *const ::core::ffi::c_char) {
    let mut pid: pid_t = 0;
    let mut in_fd: [::core::ffi::c_int; 2] = [0; 2];
    let mut out_fd: [::core::ffi::c_int; 2] = [0; 2];
    let mut fdset: fd_set = fd_set { fds_bits: [0; 16] };
    let mut readset: fd_set = fd_set { fds_bits: [0; 16] };
    let mut tv: timeval = timeval {
        tv_sec: 0,
        tv_usec: 0,
    };
    let mut sel: ::core::ffi::c_int = 0;
    let mut idx: ::core::ffi::c_int = 0;
    let mut state: ::core::ffi::c_int = 0;
    let mut buffer: [::core::ffi::c_char; 1024] = [0; 1024];
    let mut c: ::core::ffi::c_char = 0;
    safe_c2rust_stack_trace_done = FALSE as gboolean;
    signal(
        SIGCHLD,
        Some(safe_c2rust_stack_trace_sigchld as unsafe extern "C" fn(::core::ffi::c_int) -> ()),
    );
    if safe_c2rust_g_unix_open_pipe_internal(&raw mut in_fd as *mut ::core::ffi::c_int, TRUE, FALSE)
        == 0
        || safe_c2rust_g_unix_open_pipe_internal(
            &raw mut out_fd as *mut ::core::ffi::c_int,
            TRUE,
            FALSE,
        ) == 0
    {
        perror(b"unable to open pipe\0" as *const u8 as *const ::core::ffi::c_char);
        _exit(0 as ::core::ffi::c_int);
    }
    pid = fork() as pid_t;
    if pid == 0 as ::core::ffi::c_int {
        let mut old_err: ::core::ffi::c_int = dup(2 as ::core::ffi::c_int);
        if old_err != -(1 as ::core::ffi::c_int) {
            let mut getfd: ::core::ffi::c_int = fcntl(old_err, F_GETFD);
            if getfd != -(1 as ::core::ffi::c_int) {
                fcntl(old_err, F_SETFD, getfd | FD_CLOEXEC);
            }
        }
        close(0 as ::core::ffi::c_int);
        safe_c2rust_checked_dup(in_fd[0 as ::core::ffi::c_int as usize]);
        close(1 as ::core::ffi::c_int);
        safe_c2rust_checked_dup(out_fd[1 as ::core::ffi::c_int as usize]);
        close(2 as ::core::ffi::c_int);
        safe_c2rust_checked_dup(out_fd[1 as ::core::ffi::c_int as usize]);
        execvp(
            *args.offset(0 as ::core::ffi::c_int as isize),
            args as *mut *mut ::core::ffi::c_char as *const *mut ::core::ffi::c_char,
        );
        if old_err != -(1 as ::core::ffi::c_int) {
            close(2 as ::core::ffi::c_int);
            (dup(old_err) == 0) as ::core::ffi::c_int;
        }
        perror(b"exec gdb failed\0" as *const u8 as *const ::core::ffi::c_char);
        _exit(0 as ::core::ffi::c_int);
    } else if pid == -(1 as ::core::ffi::c_int) {
        perror(b"unable to fork\0" as *const u8 as *const ::core::ffi::c_char);
        _exit(0 as ::core::ffi::c_int);
    }
    let mut __i: ::core::ffi::c_uint = 0;
    let mut __arr: *mut fd_set = &raw mut fdset;
    __i = 0 as ::core::ffi::c_uint;
    while (__i as usize)
        < (::core::mem::size_of::<fd_set>() as usize)
            .wrapping_div(::core::mem::size_of::<__fd_mask>() as usize)
    {
        (*__arr).fds_bits[__i as usize] = 0 as __fd_mask;
        __i = __i.wrapping_add(1);
    }
    fdset.fds_bits[(out_fd[0 as ::core::ffi::c_int as usize] / __NFDBITS) as usize] |=
        ((1 as ::core::ffi::c_ulong) << out_fd[0 as ::core::ffi::c_int as usize] % __NFDBITS)
            as __fd_mask;
    safe_c2rust_checked_write(
        in_fd[1 as ::core::ffi::c_int as usize],
        b"set width unlimited\n\0" as *const u8 as *const ::core::ffi::c_char as gconstpointer,
        20 as gsize,
    );
    safe_c2rust_checked_write(
        in_fd[1 as ::core::ffi::c_int as usize],
        b"backtrace\n\0" as *const u8 as *const ::core::ffi::c_char as gconstpointer,
        10 as gsize,
    );
    safe_c2rust_checked_write(
        in_fd[1 as ::core::ffi::c_int as usize],
        b"p x = 0\n\0" as *const u8 as *const ::core::ffi::c_char as gconstpointer,
        8 as gsize,
    );
    safe_c2rust_checked_write(
        in_fd[1 as ::core::ffi::c_int as usize],
        b"quit\n\0" as *const u8 as *const ::core::ffi::c_char as gconstpointer,
        5 as gsize,
    );
    idx = 0 as ::core::ffi::c_int;
    state = 0 as ::core::ffi::c_int;
    loop {
        readset = fdset;
        tv.tv_sec = 1 as __time_t;
        tv.tv_usec = 0 as __suseconds_t;
        sel = select(
            FD_SETSIZE,
            &raw mut readset,
            ::core::ptr::null_mut::<fd_set>(),
            ::core::ptr::null_mut::<fd_set>(),
            &raw mut tv,
        );
        if sel == -(1 as ::core::ffi::c_int) {
            break;
        }
        if sel > 0 as ::core::ffi::c_int
            && readset.fds_bits[(out_fd[0 as ::core::ffi::c_int as usize] / __NFDBITS) as usize]
                & ((1 as ::core::ffi::c_ulong)
                    << out_fd[0 as ::core::ffi::c_int as usize] % __NFDBITS)
                    as __fd_mask
                != 0 as __fd_mask
        {
            if read(
                out_fd[0 as ::core::ffi::c_int as usize],
                &raw mut c as *mut ::core::ffi::c_void,
                1 as size_t,
            ) != 0
            {
                match state {
                    0 => {
                        if c as ::core::ffi::c_int == '#' as i32 {
                            state = 1 as ::core::ffi::c_int;
                            idx = 0 as ::core::ffi::c_int;
                            let fresh0 = idx;
                            idx = idx + 1;
                            buffer[fresh0 as usize] = c;
                        }
                    }
                    1 => {
                        if idx < BUFSIZE {
                            let fresh1 = idx;
                            idx = idx + 1;
                            buffer[fresh1 as usize] = c;
                        }
                        if c as ::core::ffi::c_int == '\n' as i32
                            || c as ::core::ffi::c_int == '\r' as i32
                        {
                            buffer[idx as usize] = 0 as ::core::ffi::c_char;
                            fprintf(
                                safe_c2rust_stdout,
                                b"%s\0" as *const u8 as *const ::core::ffi::c_char,
                                &raw mut buffer as *mut ::core::ffi::c_char,
                            );
                            state = 0 as ::core::ffi::c_int;
                            idx = 0 as ::core::ffi::c_int;
                        }
                    }
                    _ => {}
                }
            }
        } else if safe_c2rust_stack_trace_done != 0 {
            break;
        }
    }
    close(in_fd[0 as ::core::ffi::c_int as usize]);
    close(in_fd[1 as ::core::ffi::c_int as usize]);
    close(out_fd[0 as ::core::ffi::c_int as usize]);
    close(out_fd[1 as ::core::ffi::c_int as usize]);
    _exit(0 as ::core::ffi::c_int);
}
